### ISSUE TITLE
У вас в задании сказано по "абсолютной" величине. Но по-факту у вас просто большее.

### ISSUE THREAD

**Issue by EdikGres** [Eb0b0/0lab_work#2]
необходимо сделать функцию abs(); Ну или просто модуль через проверку делать. Выполнено задание некорректно =(
https://github.com/Eb0b0/0lab_work/blob/1d4503777f2c3d2778cec12c58d2365b9b41a558/1.c#L4

**Comment by EdikGres** [comment]
Я имею ввиду, если я подам -100, 4, 50. Больший будет у вас 50, а не 100.

**Comment by Eb0b0** [comment]
а как -100, может быть больше 50?

**Comment by EdikGres** [comment]
Ну смотри, у тебя в задании по абсолютной величине. Грубо говоря по модулю числа ты расматриваешь.
вход: -100, 4,50.
Проверка идёт между: |-100|, |4|, |50| Какое больше? Правильно, 100 =)

**Comment by Eb0b0** [comment]
спасибо, не до конца поняла условия задания. Исправлю)

**Comment by EdikGres** [comment]
ну я имел ввиду про это: 
```cpp
if(x < 0)
    x*=-1;
```
Ну думаю посыл ясен. Там уже сами решите как реализовать. Удачи ^^
